[opener]
play = [
  { run = 'vlc "$@"', orphan = true, desc = "VLC", for = "macos"},
  { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]
